version: '3'
services:
  web:
    build: site
    container_name: webserver
    ports :
     - "8080:8080"
    volumes:
     - ./site/html:/var/www/html/

  server-reverse-proxy:
    build: server-proxy
    container_name: reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - "web"


