version: '3.9'
services:
  web:
    build: site
    container_name: webserver
    volumes:
     - ./site/html:/var/www/html/

  server-reverse-proxy:
    build: server-proxy
    container_name: reverse-proxy
    ports:
      - "5000:443"


